# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-22 00:36
from __future__ import unicode_literals

import commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eid',
            field=models.CharField(default=commons.utils.get_uuid, max_length=32),
        ),
    ]
