# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-22 00:40
from __future__ import unicode_literals

import commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0003_auto_20160328_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='eid',
            field=models.CharField(default=commons.utils.get_uuid, max_length=32),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='eid',
            field=models.CharField(default=commons.utils.get_uuid, max_length=32),
        ),
    ]
