# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0005_auto_20160524_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupproduct',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='eid',
        ),
    ]
