# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20160524_0157'),
        ('product_groups', '0006_auto_20160524_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='created_by',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
