# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_eid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
