# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-10 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20160626_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cellphone',
        ),
    ]
