# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='voucher',
            field=models.TextField(default='{}'),
        ),
    ]
