# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-10 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.FloatField()),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
                'permissions': (),
            },
        ),
    ]
