# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='short_name',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
