# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160523_2359'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='products.Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouses.Warehouse')),
            ],
            options={
                'verbose_name': 'warehouse_product',
                'verbose_name_plural': 'warehouse_products',
                'permissions': (),
            },
        ),
    ]
