# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_warehouse'),
        ('warehouses', '0002_warehouseproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouses.Warehouse')),
            ],
            options={
                'verbose_name': 'warehouse_stock',
                'verbose_name_plural': 'warehouse_stock',
                'permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='WarehouseProduct',
        ),
    ]
