# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_remove_warehouse_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='eid',
        ),
    ]
