# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-22 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160522_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_per_uom',
            new_name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.DeleteModel(
            name='UOM',
        ),
    ]
