# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
        ('products', '0007_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_per_unit',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.Warehouse'),
        ),
    ]
