# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160523_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
    ]
