# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0009_remove_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.Company'),
        ),
    ]
