# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-19 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uoms', '0002_uom_short_name'),
        ('products', '0014_auto_20160618_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uoms.UOM'),
        ),
    ]
