# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-26 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_uom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_price',
            new_name='price_per_unit',
        ),
    ]
