# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20160626_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
